[package]
name = "parser"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = "0.7.14"
util = { path = "../util" }
num-traits = "0.2.19"
