[package]
edition = "2024"
name = "aoc"
version = "0.1.0"

[profile.dev]
split-debuginfo = "unpacked"

[dependencies.day01]
path = "./day01"

[dependencies.day02]
path = "./day02"

# [dependencies.day03]
# path = "./day03"
#
# [dependencies.day04]
# path = "./day04"
#
# [dependencies.day05]
# path = "./day05"
#
# [dependencies.day06]
# path = "./day06"
#
# [dependencies.day07]
# path = "./day07"
#
# [dependencies.day08]
# path = "./day08"
#
# [dependencies.day09]
# path = "./day09"
#
# [dependencies.day10]
# path = "./day10"
#
# [dependencies.day11]
# path = "./day11"
#
# [dependencies.day12]
# path = "./day12"

[dependencies.util]
path = "./util"

[workspace]
members = [
    "day01",
    "day02",
    "parser",
    "util",
]
