[package]
name = "day10"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
parser = { path = "../parser" }
itertools = "0.14"
winnow = "0.7.14"
